name: coinlib_flutter
description:
  A flutter wrapper for coinlib, a straight-forward, modular library for
  Peercoin and other Satoshi-based UTXO blockchains
version: 4.0.0
repository: https://github.com/peercoin/coinlib

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=2.17.0"

dependencies:
  coinlib: ^4.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
      android:
        ffiPlugin: true
      windows:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      web:
